name: Android CD - Build APK & AppBundle
run-name: Deploy by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    types: [labeled, opened, synchronize, reopened]

jobs:
  build:
    name: Android Flutter Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Versión actualizada

      - name: Setup Java JDK
        uses: actions/setup-java@v4 # Versión actualizada
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Create .env file
        run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > .env

      - name: Get Flutter Packages
        run: flutter pub get

      - name: Clean Flutter Project
        run: flutter clean

      - name: Build Flutter APK
        run: flutter build apk --release

      - name: Build Flutter AppBundle
        run: flutter build appbundle --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AppBundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-appbundle
          path: build/app/outputs/bundle/release/app-release.aab
